recovery_behavior_enables: true

recovery_behaviors: #[]
  - name: "super_conservative_reset"
    type: "clear_costmap_recovery/ClearCostmapRecovery"
  - name: "conservative_reset"
    type: "clear_costmap_recovery/ClearCostmapRecovery"
  - name: "agressive_reset"
    type: "clear_costmap_recovery/ClearCostmapRecovery"
  #- name: "move_slow_and_clear"
  #type: "move_slow_and_clear/MoveSlowAndClear"

super_conservative_reset:
  reset_distance: 1.5
  layer_names: ["laser_obstacle_layer", "depth_obstacle_layer"]

conservative_reset:
  reset_distance: 0.5
  layer_names: ["laser_obstacle_layer", "depth_obstacle_layer"]

aggressive_reset:
  reset_distance: 0.1
  layer_names: ["laser_obstacle_layer", "depth_obstacle_layer"]
#move_slow_and_clear:
#  clearing_distance: 0.5
#  limited_trans_speed: 0.25
#  limited_rot_speed: 0.45
#  limited_distance: 0.3
