global_costmap:
  global_frame: map
  robot_base_frame: base_link
  transform_tolerance: 0.2
  update_frequency: 0.3
  publish_frequency: 0.5
  static_map: false
  rolling_window: true

  width: 100.0
  height: 100.0
  resolution: 0.05

  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"} 
    - {name: laser_obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: global_inflation_layer, type: "costmap_2d::InflationLayer"}
