local_costmap:
  global_frame: map
  robot_base_frame: base_link
  transform_tolerance: 0.2
  update_frequency: 3 
  publish_frequency: 2
  static_map: false
  always_send_full_costmap: true
  rolling_window: true
  width: 8
  height: 8
  resolution: 0.05


  plugins:   
    - {name: static_layer, type: "costmap_2d::StaticLayer"} 
    - {name: laser_obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: point_obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: local_inflation_layer, type: "costmap_2d::InflationLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
